project:
  type: website
  output-dir: docs

website:
  favicon: files/favicon.png
 
  back-to-top-navigation: true
 
  google-analytics:
    tracking-id: "G-GJVKVH4E2Y"

  navbar:
    style: "docked"
    background: transparent
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: cv.qmd
        text: CV

format:
  html:
    theme:
      light: [flatly, "styles/theme-light.scss"]
      dark: [darkly, "styles/theme-dark.scss"]
    css:
      - styles/styles.css
    font:
      text: "Open Sans"
    fontsize: 11pt
    toc: false

bluesky-comments:
  mute-patterns:
    - "📌"
    - "🔥"
    - "/\\bspam\\b/i"  # regex pattern
  mute-users:
    - "did:plc:1234abcd"
  filter-empty-replies: true
  visible-comments: 3
  visible-subcomments: 3

editor: visual

