project:
  type: website
  output-dir: docs

website:
  favicon: files/favicon.png
  back-to-top-navigation: true
  google-analytics:
    tracking-id: "G-GJVKVH4E2Y"
  navbar:
    style: "docked"
    background: transparent
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    css:
      - styles/styles.css
    toc: true

editor: visual

