project:
  type: website
  output-dir: docs

website:
  # title: "Guillem Maya"
  # description: "A data economics blog and portfolio by Guillem Maya"
  site-url: https://guillemmaya.com
  repo-url: https://github.com/guillemmaya92/guillemmaya.com
  favicon: files/favicon.png
  back-to-top-navigation: true
  google-analytics:
    tracking-id: "G-GJVKVH4E2Y"
  navbar:
    style: "docked"
    background: transparent
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: cv.qmd
        text: CV
  page-footer:
    border: false
    left: |
      Powered by [{{< iconify simple-icons:quarto >}} Quarto](https://quarto.org).

format:
  html:
    theme:
      light: [flatly, "styles/theme-light.scss"]
      dark: [darkly, "styles/theme-dark.scss"]
    css:
      - styles/styles.css
    font:
      text: "Open Sans"
    fontsize: 11pt
    date-format: medium
    lang: en
    toc: false

bluesky-comments:
  mute-patterns:
    - "📌"
    - "🔥"
    - "/\\bspam\\b/i"  # regex pattern
  mute-users:
    - "did:plc:1234abcd"
  filter-empty-replies: true
  visible-comments: 3
  visible-subcomments: 3

editor: visual

